import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern using Viral TikTok Slideshows — the free preview, the $2 unlock, accounts, payments, and acceptable use.",
  alternates: { canonical: "/terms" },
};

const SECTIONS = [
  {
    title: "1. Acceptance of these terms",
    body: `By accessing or using viraltiktokslideshows.com (the "Service"), you agree to be bound by these Terms of Service. If you don't agree, don't use the Service. We may update these terms from time to time; if we make material changes we'll update the date below and, where reasonable, let you know.`,
  },
  {
    title: "2. What the Service does",
    body: `You type an idea. We use third-party AI models to generate a short slide-deck script and background images from it. The hook slide is shown to you for free. Unlocking the full slideshow — every slide, every image, no watermark, downloadable — is a one-time $2 payment per slideshow.`,
  },
  {
    title: "3. Accounts",
    body: `Unlocking a slideshow requires an account. You can create one with Google OAuth or a passwordless "magic link" emailed to you — we don't ask you to set or store a password. You're responsible for keeping access to your email/Google account secure, since that's what controls sign-in.`,
  },
  {
    title: "4. Payments",
    body: `Payments are processed by Dodo Payments, a third-party payment processor. We never see or store your full card details — Dodo handles that. The $2 unlock is a one-time charge per slideshow, not a subscription. Refund requests can be sent to the support address below and are handled case by case.`,
  },
  {
    title: "5. Your content and what you can submit",
    body: `You keep ownership of the ideas you type in and the slideshows generated from them once you've unlocked them. In order to generate and deliver that content, you grant us a license to process, store, and transmit what you submit — including sending it to the third-party AI providers listed in our Privacy Policy.

You agree not to submit ideas intended to generate illegal content, content that infringes someone else's rights, hateful or harassing content, sexual content involving minors, or anything designed to abuse, exploit, or overload the Service. We can remove content or suspend accounts that violate this.`,
  },
  {
    title: "6. AI-generated content — no guarantees",
    body: `Slide text and images are generated by third-party AI models (currently OpenRouter/Google Gemini for text and Ideogram for images). AI output can be inaccurate, generic, unexpectedly similar to other users' output, or occasionally fail safety checks and come back without an image. We don't guarantee originality, accuracy, or fitness for any particular purpose, and we're not responsible for how you use generated content once it's yours.`,
  },
  {
    title: "7. Free preview limits & fair use",
    body: `The free hook-slide preview is rate-limited per visitor to keep the Service usable and to control our own costs (every generation costs us real money in AI usage). We use Cloudflare Turnstile to filter automated/bot traffic. Attempting to bypass these limits, scrape the Service, or automate account creation is a violation of these terms.`,
  },
  {
    title: "8. Intellectual property",
    body: `The Service itself — its design, code, and branding — belongs to us. These terms don't grant you any rights to that beyond what's needed to use the Service normally.`,
  },
  {
    title: "9. Disclaimers & limitation of liability",
    body: `The Service is provided "as is," without warranties of any kind. To the maximum extent permitted by law, we aren't liable for indirect, incidental, or consequential damages arising from your use of the Service. Our total liability for any claim is capped at the amount you paid us in the 3 months before the claim arose.`,
  },
  {
    title: "10. Termination",
    body: `You can stop using the Service and ask us to delete your account at any time by contacting us. We can suspend or terminate accounts that violate these terms.`,
  },
  {
    title: "11. Governing law",
    body: `These terms are governed by the laws of the jurisdiction in which the Service operator is established, without regard to conflict-of-law principles. Consult a lawyer if you need this tailored to a specific jurisdiction.`,
  },
  {
    title: "12. Contact",
    body: `Questions about these terms: support@viraltiktokslideshows.com.`,
  },
];

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-20">
      <h1 className="font-display text-3xl font-bold text-foreground sm:text-4xl">
        Terms of Service
      </h1>
      <p className="mt-3 text-sm text-muted-foreground">Last updated July 14, 2026</p>

      <p className="mt-6 rounded-2xl border border-border bg-muted/40 p-4 text-sm text-muted-foreground">
        This is a general template covering how the Service actually works, not a substitute for
        legal advice — have a lawyer review it before relying on it for compliance purposes.
      </p>

      <div className="mt-10 flex flex-col gap-8">
        {SECTIONS.map((section) => (
          <section key={section.title}>
            <h2 className="font-display text-lg font-bold text-foreground">{section.title}</h2>
            <p className="mt-2 whitespace-pre-li